services:
  postgres:
    image: postgres:16
    container_name: os_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: America/Maceio
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - os_data:/var/lib/postgresql/data

volumes:
  os_data: