spring.application.name=api-os
server.forward-headers-strategy=framework

spring.config.import=optional:file:.env[.properties]

# Definir perfil ativo
spring.profiles.active=${SPRING_PROFILE:dev}
spring.jpa.open-in-view=false

# 0.0.0.0 permite que o celular na mesma rede acesse a api
server.address=0.0.0.0
server.port=${SERVER_PORT:8081}

# Datas gravadas em UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC